### ISSUE TITLE
Выделение основных стилей в отдельные файлы

### ISSUE THREAD

**Issue by agentgoblin** [korney4eg/gg_staff#5]
Я тут что подумал. Крутил чат и понял, что мне не нравится как он выглядит в плане расположения ников и сообщений. У меня настроено, что всё выводится в виде таблицы - слева ники, справа сообщения и они не смешиваются. Это настраивается в опциях чата, но для этого надо быть залогиненным, а OBS грузит чат как анонимус. Вынул стили, допилил отображение в OBS так, как мне надо и понял, что один файл со стилями получается сильно перегруженным. Особенно учитывая кастомизацию.

Поэтому подумал, что стоит создать несколько файлов по стилевому признаку. Чат в обычном виде. Чат в две колонки. Плюс варианты каждого стиля, где переопределён цвет в монохром, чтобы поменьше лазать руками, т.к. затрагиваются общие классы ников юзеров, редактирование для неопытного человека становится сложнее.

`Плюсы:` Пользователь выбрал самый близкий для себя стиль, накатил его, изменения надо делать минимальные (цвет/прозрачность через переменную настроить и в большинстве случаев этого достаточно).

`Минусы:` Придётся в случае проблем или новых фич стиля, общих для файлов, не забывать фиксить несколько файлов. Возможно стоит подумать над генератором файлов стилей по шаблонам (по реализации идея есть).

**Comment by korney4eg** [comment]
Получается что-то типа "тем" оформления?

**Comment by agentgoblin** [comment]
Да, что-то вроде тем оформления.

Т.е. идея какая:
- отдельные блоки правил CSS разнесены по набору файлов
- файл описания темы содержит имена файлов с CSS для включения в себя
- генератор читает файлы описания темы, собирает воедино файл CSS из кусочков и кладёт в отдельную директорию
- в итоге получаем пачку тем в отдельной директории, выбирай любую по вкусу, минимально правь, если надо и отдавай в ОБС

Понятно что все хотелки и самые извращённые фантазии охвачены не будут, но хотя бы основные запросы кастомизации возможно удастся удовлетворить.

А далее тот же генератор можно будет использовать для сборки тем в интерактивном режиме, например. На ходу по тому, что накликал пользователь, генерить файл описания темы и выдавать результат. В т.ч. к какому-нибудь веб-сервису прикрутить.

**Comment by agentgoblin** [comment]
Сейчас растащил в отдельные файлы правила, завтра буду создавать файлы описаний тем и генератор накатаю, если ничего не случится и у меня будет время.

**Comment by korney4eg** [comment]
Слушай.
Раз мы тут уже генерируем один CSS из нескольких, может это как-нибудь подружить с https://goodgame.makvaz.com/ ?

И там и там получается генерация, тогда зачем развивать по-отдельности, если можно совместить?

Конечно хорошо бы продумать дизайн, каким образом выкликивать параметры, и каким - выбирать тему из списка.

**Comment by agentgoblin** [comment]
Я на самом деле думал об этом. Чтобы этот сервис мог использовать генератор при необходимости.

**Comment by korney4eg** [comment]
Я вот думаю, хорошо бы собраться в онлайне, или лучше на стриме.
Ты до скольки обычно вечером сидишь? Можно было бы пообщаться так.

**Comment by agentgoblin** [comment]
Сделал прототип. Можно поглядеть изменения на ветке [generator](https://github.com/agentgoblin/gg_stuff/tree/generator).

Для примера генерируется две темы - дефолт и дефолт без иконок зрителей.

**Comment by agentgoblin** [comment]
Прототип готов, запрос на слияние тут: https://github.com/korney4eg/gg_stuff/pull/10

Думаю здесь пока всё, обсуждение по web-странице лучше вынести отдельно, если потребуется.

**Comment by agentgoblin** [comment]
Функционал в мастере, задача выполнена.
