### ISSUE TITLE
Не перекрашиваются блоки с информацией о новом задании

### ISSUE THREAD

**Issue by agentgoblin** [korney4eg/gg_staff#6]
Всплывашка, которая отображает новое задание для стримера (не путать с закреплёнными заданиями), не перекрашивается при активации перекраски текста.

**Comment by agentgoblin** [comment]
Также надо скрыть элементы управления и рюшечки.

**Comment by korney4eg** [comment]
@agentgoblin у тебя есть пример чатика, где сейчас отображает задания?

**Comment by agentgoblin** [comment]
Это не отображение закреплённых заданий (они у нас уже скрываются, https://github.com/korney4eg/gg_stuff/commit/11ae91d414bbe6a8b5964dffc8a1ebb821ad1fd8). Это всплывашка в чате, которая появляется, когда ты добавляешь новые задания. В любом чате можно проверить, просто добавляя задания для стримера.

Я вчера её выдернул из чата, разобрал на теги, но не оформлял. Поэтому можно подождать вечера - я оформлю всё в код.

**Comment by agentgoblin** [comment]
А так вообще Utan постоянно прикреплёнными три задания держит уже который месяц.

**Comment by agentgoblin** [comment]
Добавил в коммите https://github.com/korney4eg/gg_stuff/commit/fe08766c319620cb806ce75fe57504eac247f1b1 на ветке [generator](https://github.com/agentgoblin/gg_stuff/tree/generator), пока не тестировал.

**Comment by agentgoblin** [comment]
Фиксы и перекрашивания тут: https://github.com/korney4eg/gg_stuff/pull/10

**Comment by agentgoblin** [comment]
Функционал в мастере, задача выполнена.
