### ISSUE TITLE
[Предложение] генерить страницу из документации

### ISSUE THREAD

**Issue by korney4eg** [korney4eg/gg_staff#8]
Есть мысль, чтобы генерить документацию в html и отображать отдельно.
С нашей стороны, особо изменений не нужно, менять нужно будет  `markdown` файл, только пользователям его можно будет отдавать как страничку в интернете(с нужным оформлением в стиле GG. Например, используя [GitHub Pages](https://pages.github.com/).

@agentgoblin что думаешь?

**Comment by agentgoblin** [comment]
В принципе нормально. Только какие преимущества перед показом markdown'а через GitHub? Просто чтобы было красивое или чтобы онлайн-форматтер стилей запилить и туда справку повесить?

И через что перегонять markdown в HTML будем? Через рекомендованный GitHub Pages Jekyll? Я его побаиваюсь, если честно, он на руби написан, а у меня с ним как-то не сложилось.

**Comment by korney4eg** [comment]
Да, jekyl.

Я им раньше генерировал бложег, потом перешёл на `gohugo`. 
Даже сейчас один сайтик хощу https://github.com/korney4eg/korney4eg.github.io без проблем.

Да, главное преимузество в том, что можно оформить в стиле ГГ.
Опять же GitHub Pages - это такой бесплатный хостинг для статичных сайтов.

**Comment by korney4eg** [comment]
получил обратную связь на дискорде ГГ. Ещё раз спасибо!
<img width="1026" alt="image" src="https://user-images.githubusercontent.com/1872070/182719041-b30e83e0-5b60-4ba0-b3e7-15b9158a9698.png">

Кстати, ты есть на дискорде ГГ?

**Comment by agentgoblin** [comment]
> Кстати, ты есть на дискорде ГГ?

Могу добавиться вечером.

**Comment by korney4eg** [comment]
закрываю, так как вроде не нужно
